import Head from 'next/head';
import { Button, Group } from '@mantine/core';
import { db } from '@firebase/firebase';
import { collection, addDoc } from 'firebase/firestore';

export default function Home() {
  const handleAdd = () => {
    const ret = addDoc(collection(db, 'users'), {
      first: 'Ada',
      last: 'Lovelace',
      born: 1815,
    });
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Group mt={50} position="center">
          <Button size="xl" onClick={handleAdd}>
            Welcome to Mantine!
          </Button>
        </Group>
      </main>
    </>
  );
}
