/* eslint-disable react-hooks/exhaustive-deps */
import { useBgLightBlue } from "hooks/useBgLightBlue";
import Head from "next/head";
import { useCallback, useEffect,useState } from "react";
import { Footer } from "src/components/Footer";
import { Header } from "src/components/Header";
import { Headline } from "src/components/Hedline";
import { Links } from "src/components/Links";
import styles from "src/styles/Home.module.css";
import useSWR from "swr";
import axios from "axios";
import { Profile } from "src/components/sample";
import Link from "next/link";


export default function Home(props) {
  const { count, handleClick } = props
  useBgLightBlue()
  return (
    <div className={styles.container}>
      <Header />
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
      <Profile/>
        <Headline title="index Page" page="index" />
        <button
          onClick={(e) => {
            handleClick(e);
          }}
        >
          button
        </button>
        <h1>{count}</h1>
        <Link href={`/post/1`}>
          <a>画面遷移1</a>
        </Link>
        <Link href={`/post/2`}>
          <a>画面遷移2</a>
        </Link>
        <Links />
      </main>
      <Footer />
    </div>
  );
}
