/* eslint-disable react-hooks/exhaustive-deps */
import { useBgLightBlue } from "hooks/useBgLightBlue";
import { useCounter } from "hooks/useCounter";
import Head from "next/head";
import { useCallback, useEffect,useState } from "react";
import { Footer } from "src/components/Footer";
import { Header } from "src/components/Headrt";
import { Headline } from "src/components/Hedline";
import { Links } from "src/components/Links";
import styles from "src/styles/Home.module.css";


export default function Home(props) {
  const { count, handleClick } = props
  useBgLightBlue()
  return (
    <div className={styles.container}>
      <Header />
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Headline title="index Page" page="index" />
        <button
          onClick={(e) => {
            handleClick(e);
          }}
        >
          button
        </button>
        <h1>{ count }</h1>
        <Links />
      </main>
      <Footer />
    </div>
  );
}
