import Head from 'next/head'
import { Headline } from '../components/Hedline'
import { Links } from '../components/Links'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Headline title="About Page" page="about"/>
        <Links/>
      </main>
    </div>
  )
}
