import Head from 'next/head'
import { Footer } from '../components/Footer'
import { Header } from '../components/Headrt'
import { Headline } from '../components/Hedline'
import { Links } from '../components/Links'
import styles from '../styles/Home.module.css'


export default function Home() {
  return (
    <div className={styles.container}>
      <Header/>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Headline title="index Page" page="index" />
        <Links />
      </main>
      <Footer />
    </div>
  )
}
